services:
  bagetter:
    container_name: bagetter
    build: .
    volumes:
      - bagetter:/data
    environment:
      Storage__Type: FileSystem
      Storage__Path: /data
      Database__Type: Sqlite
      Database__ConnectionString: Data Source=/data/db/bagetter.db
      Search__Type: Database
      AllowPackageOverwrites: ${ALLOW_PACKAGE_OWERWRITERS}

volumes:
  bagetter:
    name: bagetter