[paths]
environments_path = "./environments"
extensions_dirs = ["extensions"]

[build]
extensions = ["guard"]
env_file_patterns = [".env", ".env.amocrm"]

[build.environments]
available = ["devcontainer", "forwarding", "letsencrypt", "step-ca"]
